### ISSUE TITLE
Form Fix

### ISSUE THREAD

**Issue by Patrickbmccabe** [kaeverens/kvwebme#12]
Hi Kae, you asked me to remind you to Fix the form element on the Mohan Memorials website, I need to change the add to cart Button to "More information" button, which will then collect un verified email information from the user

I would also like to Email them a PDF of the Gravestone that they clicked about, , ,

**Comment by Patrickbmccabe** [comment]
Also, , I need to add a contact form to the site, , , am I missing something?
![formelement](https://f.cloud.github.com/assets/3995542/317570/f82cdc5a-9877-11e2-8fb5-b4adf98d12d0.png)

**Comment by kaeverens** [comment]
nice screenshot! that makes a brilliant bug report.

all you need to do is re-enable to Form plugin (in Site Options > Plugins)

**Comment by kaeverens** [comment]
whoops - accidentally closed when it wasn't quite completed.

**Comment by kaeverens** [comment]
to change the "Add to Cart" to "More Information", you just need to change this code:
{{PRODUCTS_BUTTON_ADD_TO_CART}}

to this code:
{{PRODUCTS_BUTTON_ADD_TO_CART text="More Information"}}

to see a list of possible codes, click on the "codes" link under the Single-View Template form in Product types.

I've made the change.
