### ISSUE TITLE
Mailing Lists plugin: Mailchimp form does not send

### ISSUE THREAD

**Issue by superstoffer** [kaeverens/kvwebme#13]
When adding a signup widget to a panel, nothing happens when you try submit the form.

**Comment by kaeverens** [comment]
/trying/ to work on this. tricky, as mailchimp is insisting that I change my password, sends an email to my registered test address (gmail account) and then gmail doesn't show it

**Comment by kaeverens** [comment]
....and I've found it. they set the wrong time on the email so it didn't appear in my recent email

**Comment by kaeverens** [comment]
ok! I can verify that there is definitely a problem. I'll have it solved in the morning :-)

**Comment by kaeverens** [comment]
Done
