### ISSUE TITLE
Menu to return <ul> and <li>

### ISSUE THREAD

**Issue by superstoffer** [kaeverens/kvwebme#14]
As we discussed on Skype, it would be great if there could be a variant of the Menu plugin, which will return only <ul> and <li> tags, making it compliant with many template and JS/CSS menu structures. 

If possible, classes round the tags would be nice, so they can be easily targeted with code.

**Comment by kaeverens** [comment]
the Plugin version of the menu already returns ul/li

I'll add a separate issue for the plain html menu.
