### ISSUE TITLE
Multiple Email noticications

### ISSUE THREAD

**Issue by Patrickbmccabe** [kaeverens/kvwebme#16]
In http://kv-11-288.sv3.kvsites.ie/ww.admin/plugin.php?_plugin=online-store&_page=emails 
![multiple email](https://f.cloud.github.com/assets/3995542/564032/c189bf30-c534-11e2-8651-51b0855e5b43.png)\
Please add the option of being abel to add multiple notoifocation recipoents for email templates

**Comment by kaeverens** [comment]
This is fixed now.

The problem was that the HTML5 email input element <input type="email"/> requires a "multiple" parameter to allow more than one: <input type="email" multiple="multiple"/>
