### ISSUE TITLE
Product Type

### ISSUE THREAD

**Issue by Patrickbmccabe** [kaeverens/kvwebme#21]
In the Webme Shopping cart, would it be an idea that in, http://paulmohanmemorials.com/ww.admin/plugin.php?_plugin=products&_page=products#
you could dupilicate a Product type, so that it would be easier to change select minutiae
P

**Comment by kaeverens** [comment]
you already can. go into product types, then click Add New Product Type. it offers to either create one from a default template, or copy an existing type.
