### ISSUE TITLE
Automated emails

### ISSUE THREAD

**Issue by billykevin** [kaeverens/kvwebme#26]
I am looking to edit the contents of automated emails, when using the register/log in plugin.

How do I edit this text? I want to include reference to my site, facebook, twitter and make other changes.

**Comment by kaeverens** [comment]
at the moment, the default text is hard-coded. I'll add a configuration for it later today so the default text can be changed.

sorry for the delay - github didn't send me a notice that there was a new issue created

**Comment by billykevin** [comment]
great thank you, please confirm by email when this is complete?

**Comment by kaeverens** [comment]
I've added a "Template" link now above the email textarea. Clicking that will pop up an editor where the default template can be edited.

Also, the textarea now shows as a rich-text editor
